version: 2.1

jobs:
  build:
    docker:
      - image: stderrat/blogbuilder:latest
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "d5:24:e8:57:5d:ce:d4:60:19:a3:0c:d9:db:ad:b0:f4"
      - run:
          name: Install node dependencies
          command: npm install
      - run:
          name: Build blog content
          command: lein run
      - run:
          name: Build search index
          command: node ./build-index.js
      # - store_artifacts:
      #     path: public/
      - persist_to_workspace:
          root: /home/deployer/project
          paths:
            - public
  deploy:
    branches:
      only:
        - master
    docker:
      - image: stderrat/blogbuilder:latest
    steps:
      - attach_workspace:
          at: /tmp/public
      - run:
          name: Checkout gh pages repository
          command: |
            mkdir -m 0700 -p $HOME/.ssh/
            echo 'github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==' >> $HOME/.ssh/known_hosts
            git clone git@github.com:stderrat/stderrat.github.io
      - run:
          name: Rsync content to github pages repository
          command: |
            rsync -av --delete --exclude '/.git/' --exclude '/CNAME' /tmp/public/public/ stderrat.github.io
      - run:
          name: Commit changes to github pages repository
          command: |
            cd stderrat.github.io
            git status
            git add -A
            git status
            git -c user.name="circleci" -c user.email="circleci@stderr.at" commit -m 'publish by circleci'
            git status
      - run:
          name: Push changes to github pages repository
          command: |
            cd stderrat.github.io
            git status
            git push origin master

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
